### ISSUE TITLE
[infra] github actions - on tag make for all platforms and release to gtihub

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#10]
NOTE: there a makefile that has commands for making for all platforms

**Comment by sbshah97** [comment]
I'd like to give this a go. Is this just go build ?

**Comment by sbshah97** [comment]
I see go build is there. Maybe add make commands for go test and go lint?

**Comment by sbshah97** [comment]
Can I give this a shot ? I've not done this before but would want to give it a try.

**Comment by championswimmer** [comment]
@sbshah97 sure why not, what's the worst that can happen, your PR will not be merged. go ahead give it a try.
