### ISSUE TITLE
Questions on Login API

### ISSUE THREAD

**Issue by manosriram** [championswimmer/onepixel_backend#12]
@championswimmer For the login API, which method are we going with since each of them have some tradeoffs.
- [JWT](https://docs.gofiber.io/contrib/jwt/)
- [Session based auth](https://docs.gofiber.io/api/middleware/basicauth/)

**Comment by championswimmer** [comment]
We'll do JWT to start with on v0.1 

We'll move to OAuth via Google etc later anyway.
