### ISSUE TITLE
Project layout and tests

### ISSUE THREAD

**Issue by harshabangi** [championswimmer/onepixel_backend#22]
The project layout does not adhere to the standard Go practice. For the Go project layout, please refer to the following link: https://github.com/golang-standards/project-layout#go-directories. In Go projects, you will typically find test files (unit tests) in the same directory as the code files. To align with the standard layout, move the test files in the 'tests' folder within their respective directories. Integration tests should be placed in the 'tests' folder.

**Comment by FaizBShah** [comment]
@championswimmer already mentioned in their tweet that this project is designed slightly different from the traditional Go project. Its following more of a Node.js project style

**Comment by thecaffeinedev** [comment]
+1 @FaizBShah. Russ Cox (one of the creators of Go) has spoken out against the [golang-standards/project-layout](https://github.com/golang-standards/project-layout/issues/117) repository.

This is the only official recommendation  https://go.dev/doc/modules/layout

**Comment by harshabangi** [comment]
@thecaffeinedev Got it. We can follow the example directory structure that is under `Server Project` in the [blog](https://go.dev/doc/modules/layout). The intention was to have cli code under `cmd`, server code under `internal`, library code under `pkg` etc.

**Comment by championswimmer** [comment]
We can move unit tests into the src folder, I am ok with that

I'll also add a VSCode and IntelliJ rule that collapses tests inside the file (on project browser) so that it doesn't pollute the view so much) 

Thanks @harshabangi @FaizBShah @thecaffeinedev for inputs

**Comment by championswimmer** [comment]
Here's what I have done to hide the test files in the explorer view. 

https://arnav.tech/nesting-test-files-under-the-main-file-in-project-view-of-visual-studio-code-and-jetbrains-ides
