### ISSUE TITLE
POST : /api/v1/urls

### ISSUE THREAD

**Issue by Tanveeshs** [championswimmer/onepixel_backend#26]
Hey @championswimmer,

I was just curious whether the creator ID is different from the group ID. And also how would we pass over the data for user are we using a token middleware?

**Comment by Tanveeshs** [comment]
Also @championswimmer could you please also give me read access I'm pretty much done with the branch

**Comment by championswimmer** [comment]
@Tanveeshs - fork and PR

**Comment by Tanveeshs** [comment]
@championswimmer added the PR. Please review

**Comment by championswimmer** [comment]
this endpoint exists now, so closing
