### ISSUE TITLE
[infra] setup github action to run all unit tests on all PRs

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#3]

**Comment by glokta1** [comment]
I can take this up!

**Comment by championswimmer** [comment]
@glokta1 

Same workflow file is fine but separate jobs is better. Would want to see separate pass/fail status of both.

**Comment by glokta1** [comment]
Huh, no idea why this didn't close after https://github.com/championswimmer/onepixel_backend/pull/8 was merged. Think we can close this now? @championswimmer
