### ISSUE TITLE
[api] /users API - v0.1.0

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#5]
### Subtasks
- [x] https://github.com/championswimmer/onepixel_backend/issues/6
- [x] https://github.com/championswimmer/onepixel_backend/issues/13

**Comment by amsanket22** [comment]
are we handling 422(unprocessable entity) here?

need to add backend validations - username should be in email format, password should be more than 6 and both fields should be mandatory

**Comment by amsanket22** [comment]
and email should be unique

**Comment by amsanket22** [comment]
some of these I can see on PR already

**Comment by championswimmer** [comment]
@amsanket22 yes all proper HTTP codes. 409 for conflict (unique email violation), and 422 for unprocessable (any parsing error in the body), 400 for everything else

**Comment by championswimmer** [comment]
this is done now
