### ISSUE TITLE
[dev] [infra] make it possible to run the local env easily with sqlite+duckdb 

### ISSUE THREAD

**Issue by championswimmer** [championswimmer/onepixel_backend#61]
When someone wants to fire it up quickly and develop, let's make it easy for them to use `sqlite` and `duckdb` instead of hosting clickhouse and postgres docker containers. 

Those are already being used for the test mode, so this should be easy to do.

**Comment by mahendrabishnoi2** [comment]
@championswimmer I would like to pick this up.

**Comment by mahendrabishnoi2** [comment]
I am assuming that we would like to have both options (postgres, clickhouse / sqlite, duckdb) for local dev.

@championswimmer Do you have any preferences on the configuration to be used for deciding which one among these 2 should be used?
1. from config file
2. from env variable

**Comment by championswimmer** [comment]
@mahendrabishnoi2 - yes would want it to have both options. 

yes via the config file should be ok. 
we can do any of the following options

1. document on Readme what to change in local.env to run with file-based DBs 
2. pass an env during running it `USE_FILE_DB=true air` or `USE_FILE_DB=true ./main`

**Comment by mahendrabishnoi2** [comment]
@championswimmer I feel like config file option is better suited as that would required least amount of code changes/hard coding since we can use dialect and db url from config file.

I have implemented the changes and tested locally. Here's the PR: https://github.com/championswimmer/onepixel_backend/pull/63
